name: 🐛 Bug Report
description: Create a report to help us improve React DataGrid
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: When I scroll past 1000 rows...
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: input
    id: reproduction-link
    attributes:
      label: Reproduction Link
      description: A link to a CodeSandbox or StackBlitz (highly recommended).
      placeholder: https://codesandbox.io/...
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
      placeholder: The grid should...
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened.
      placeholder: Instead, the grid...
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: Browsers
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - All Browsers
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: React DataGrid Version
      placeholder: v1.0.0
    validations:
      required: true
  - type: input
    id: react-version
    attributes:
      label: React Version
      placeholder: 18.2.0
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, error messages, etc.).
      placeholder: Error message, screenshots, etc.
